### ISSUE TITLE
Support for go install

### ISSUE THREAD

**Issue by gingermusketeer** [fgrosse/prox#10]
Hi, 

I am keen to try out your tool but I noticed that it doesn't support installation via `go install github.com/fgrosse/prox@latest` due to not having a main.go with a main package and main function. Would you be open to adding support for `go install` as it is a bit easier to install?

**Comment by fgrosse** [comment]
Hi Max, thanks for your request. You can install prox with `go install` like this:

```shell
❯ go install github.com/fgrosse/prox/...@latest
go: downloading github.com/spf13/cobra v0.0.3
go: downloading github.com/spf13/viper v1.2.1
go: downloading github.com/spf13/pflag v1.0.2
go: downloading github.com/mitchellh/mapstructure v1.0.0
go: downloading github.com/spf13/cast v1.2.0
go: downloading golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
go: downloading golang.org/x/text v0.3.0

❯ which prox
~/go/bin/prox
```

Alternatively, you can also install without the `...` if you install the complete path to the binary command:

```shell
# Delete previously built prox binary
❯ rm $(which prox)

❯ go install github.com/fgrosse/prox/cmd/prox@latest

❯ which prox
~/go/bin/prox
```
