### ISSUE TITLE
Prefer to give the same process color to processes of different name lengths

### ISSUE THREAD

**Issue by cornelk** [fgrosse/prox#4]
For example, currently:

| process | color |
| - | - |
| test | blue |
| test123 | yellow |
| test12 | red |
| word | blue |

For better visibility/differentiation of processes:

| process | color |
| - | - |
| test | blue |
| test123 | yellow |
| test12 | blue |
| word | red |

**Comment by fgrosse** [comment]
I'm not 100% sure I understand the request. The idea of the colour palette is to have different colors for different processes so its easy to find logs for a specific process at a glance. 

In your example (second table), can you explain whyt `test` and `test12`would get the same color but not `test123`. Also how would this help readability?

In the first table, I assume its just an example if the colour palette would only have three colours and you want to avoid that if a colour is reused, its done for processes that have a different name length?

**Comment by fwolfst** [comment]
Issue looks pretty stale.
