### ISSUE TITLE
Failed to open unix socket: listen unix .prox.sock: bind: address already in use

### ISSUE THREAD

**Issue by GeoffreyPlitt** [fgrosse/prox#9]
Hello,

I love this utility! It's been working well for me, via an SSH shell into my Raspberry Pi device.

But when I connect to the same device using minicom to run a serial session over a USB to the Pi's debug port (which works well for most commands), prox fails with:

prox          │ [ERROR] Failed to open unix socket: listen unix .prox.sock: bind: address already in use

Is there a reason prox can't run over this kind of connection? Why is it binding a unix socket?

**Comment by fgrosse** [comment]
Hey Geoffrey,

Can you check if there is a dot file called `.prox.sock` in the directory from which you are executing `prox`? If you find one, you can just delete it.

Maybe it's a leftover from a previously failed execution. The socket file is used to communicate with the running prox instance in another terminal, e.g. to list processes or stream log output :)

**Comment by GeoffreyPlitt** [comment]
That worked, thanks!
